<script setup>
import { computed,onMounted,ref } from 'vue';
import DashboardLayout from '../../layouts/DashboardLayout.vue';
import { createIncome,getIncome } from '../../services/income.service.js';
import { useAuthStore } from '../../stores/auth.store.js';
const auth=useAuthStore();const records=ref([]);const cycle=ref(null);const summary=ref({fines:0,loan_interest:0,service_charges:0,other:0,total_income:0,expenses:0,profit:0});const loading=ref(false);const saving=ref(false);const showForm=ref(false);const errorMessage=ref('');const successMessage=ref('');const filter=ref('all');const form=ref({category:'service_charge',amount:'',payer:'',description:'',reference:'',income_date:new Date().toISOString().slice(0,10)});
const canCreate=computed(()=>['admin','treasurer'].includes(auth.user?.role));const filtered=computed(()=>filter.value==='all'?records.value:records.value.filter(item=>item.status===filter.value));const currency=value=>new Intl.NumberFormat('en-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(value||0);const date=value=>value?new Date(value).toLocaleDateString():'—';const label=value=>value==='service_charge'?'Service charge':'Other income';
const load=async()=>{loading.value=true;errorMessage.value='';try{const response=await getIncome();cycle.value=response.data?.data?.cycle||null;records.value=response.data?.data?.records||[];summary.value=response.data?.data?.summary||summary.value;}catch(error){errorMessage.value=error.response?.data?.message||'Unable to load income.';}finally{loading.value=false;}};
const close=()=>{showForm.value=false;errorMessage.value='';form.value={category:'service_charge',amount:'',payer:'',description:'',reference:'',income_date:new Date().toISOString().slice(0,10)};};
const submit=async()=>{saving.value=true;errorMessage.value='';try{const response=await createIncome({...form.value,amount:Number(form.value.amount),payer:form.value.payer||null,reference:form.value.reference||null});successMessage.value=response.data?.message||'Income submitted for approval.';close();await load();}catch(error){errorMessage.value=error.response?.data?.message||'Unable to submit income.';}finally{saving.value=false;}};onMounted(load);
</script>
<template><DashboardLayout page-title="Income" page-subtitle="Non-saving income and profit">
<section class="page-header"><div class="page-header-copy"><p class="page-header-label">{{ cycle?.name||'No active cycle' }}</p><h2>Income & actual profit</h2><p class="page-header-text mb-0">Track fines, realized loan interest, service charges, and other income without treating member savings as profit.</p></div><button v-if="canCreate&&cycle" class="btn btn-primary" @click="showForm=true"><i class="bi bi-plus-lg me-2"></i>Record income</button></section>
<div v-if="errorMessage&&!showForm" class="alert alert-warning">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div><div v-if="!cycle&&!loading" class="alert alert-info">Activate a financial cycle before recording income.</div>
<section class="income-grid"><article><span class="income-icon fines"><i class="bi bi-exclamation-diamond"></i></span><small>Collected fines</small><strong>{{ currency(summary.fines) }}</strong><p>Automatic from paid penalties</p></article><article><span class="income-icon interest"><i class="bi bi-percent"></i></span><small>Realized loan interest</small><strong>{{ currency(summary.loan_interest) }}</strong><p>Interest portion of repayments</p></article><article><span class="income-icon charges"><i class="bi bi-receipt"></i></span><small>Service charges</small><strong>{{ currency(summary.service_charges) }}</strong><p>Approved non-saving charges</p></article><article><span class="income-icon other"><i class="bi bi-cash-coin"></i></span><small>Other income</small><strong>{{ currency(summary.other) }}</strong><p>Approved miscellaneous income</p></article></section>
<section class="profit-card"><div><span>Actual cycle profit</span><strong :class="{negative:Number(summary.profit)<0}">{{ currency(summary.profit) }}</strong><small>Total income {{ currency(summary.total_income) }} − approved expenses {{ currency(summary.expenses) }}</small></div><i class="bi bi-graph-up-arrow"></i></section>
<section class="card panel-card"><div class="card-body"><div class="income-head"><div><h5 class="mb-1">Manual income register</h5><p class="text-muted mb-0">Fines and interest are calculated automatically.</p></div><div class="filters"><button v-for="item in [['all','All'],['pending','Pending'],['approved','Approved'],['rejected','Rejected']]" :key="item[0]" :class="{active:filter===item[0]}" @click="filter=item[0]">{{ item[1] }}</button></div></div><div class="table-responsive"><table class="table align-middle mb-0 income-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Payer</th><th>Reference</th><th>Requested by</th><th>Status</th><th class="text-end">Amount</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="text-center py-5">Loading income...</td></tr><tr v-else-if="!filtered.length"><td colspan="8" class="text-center py-5">No manual income records.</td></tr><tr v-for="item in filtered" v-else :key="item.id"><td>{{ date(item.income_date) }}</td><td><span class="category">{{ label(item.category) }}</span></td><td><strong>{{ item.description }}</strong></td><td>{{ item.payer||'—' }}</td><td><code>{{ item.reference||`INC-${item.id}` }}</code></td><td>{{ item.requested_by_name }}</td><td><span class="status" :class="item.status">{{ item.status }}</span></td><td class="text-end"><strong>{{ currency(item.amount) }}</strong></td></tr></tbody></table></div></div></section>
<div v-if="showForm" class="modal-backdrop"><div class="modal-panel"><div class="modal-panel-header"><div><p class="page-header-label mb-2">{{ cycle?.name }}</p><h5 class="mb-0">Record non-saving income</h5></div><button class="btn btn-close" @click="close"></button></div><form class="mt-3" @submit.prevent="submit"><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label">Income category</label><select v-model="form.category" class="form-select"><option value="service_charge">Service charge</option><option value="other">Other income</option></select></div><div class="col-12 col-md-6"><label class="form-label">Income date</label><input v-model="form.income_date" class="form-control" type="date" required /></div><div class="col-12 col-md-6"><label class="form-label">Amount (TZS)</label><input v-model="form.amount" class="form-control" type="number" min="1" step="0.01" required /></div><div class="col-12 col-md-6"><label class="form-label">Received from <span class="text-muted">(optional)</span></label><input v-model="form.payer" class="form-control" /></div><div class="col-12"><label class="form-label">Description</label><textarea v-model="form.description" class="form-control" rows="3" required></textarea></div><div class="col-12"><label class="form-label">Receipt / reference <span class="text-muted">(optional)</span></label><input v-model="form.reference" class="form-control" /></div></div><div class="approval-note"><i class="bi bi-shield-check"></i><span><strong>Approval required</strong>Only approved income affects the ledger and cycle profit.</span></div><p v-if="errorMessage" class="text-danger small mt-3">{{ errorMessage }}</p><div class="modal-actions"><button type="button" class="btn btn-outline-secondary" @click="close">Cancel</button><button class="btn btn-primary" :disabled="saving">{{ saving?'Submitting...':'Submit for approval' }}</button></div></form></div></div>
</DashboardLayout></template>
<style scoped>
.income-grid{display:grid;grid-template-columns:1fr;gap:.7rem;margin-bottom:1rem}.income-grid article{display:grid;grid-template-columns:auto 1fr;gap:.1rem .65rem;padding:.9rem;border:1px solid #ebe9ef;border-radius:11px;background:#fff}.income-icon{grid-row:span 3;width:2.2rem;height:2.2rem;display:grid;place-items:center;border-radius:8px}.income-icon.fines{background:#fff0f1;color:#c34653}.income-icon.interest{background:#eaf9f1;color:#168657}.income-icon.charges{background:#eef5ff;color:#2877c7}.income-icon.other{background:#f0edff;color:#7055dc}.income-grid small{color:#89858f;font-size:.64rem}.income-grid strong{font-size:.95rem}.income-grid p{margin:0;color:#9a96a0;font-size:.6rem}.profit-card{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem;padding:1.1rem;border-radius:13px;background:linear-gradient(135deg,#2d2440,#6749c7);color:#fff}.profit-card span,.profit-card strong,.profit-card small{display:block}.profit-card span{color:#cbbef5;font-size:.65rem;text-transform:uppercase}.profit-card strong{margin:.3rem 0;font-size:1.5rem}.profit-card strong.negative{color:#ffbec5}.profit-card small{color:rgba(255,255,255,.6);font-size:.65rem}.profit-card>i{font-size:2rem;color:#cbbef5}.income-head{display:flex;flex-direction:column;gap:.8rem;margin-bottom:1rem}.filters{display:flex;gap:.25rem;padding:.25rem;border-radius:8px;background:#f4f3f6}.filters button{padding:.4rem .55rem;border:0;border-radius:6px;background:transparent;color:#77727e;font-size:.64rem}.filters button.active{background:#fff;color:#7055dc;box-shadow:0 1px 4px rgba(20,18,28,.08)}.income-table{min-width:920px}.category{padding:.28rem .5rem;border-radius:6px;background:#f0edff;color:#7055dc;font-size:.63rem}.income-table code{color:#7055dc;font-size:.64rem}.status{display:inline-flex;padding:.27rem .55rem;border-radius:999px;font-size:.62rem}.status.pending{background:#fff5dd;color:#a56a00}.status.approved{background:#eaf9f1;color:#168657}.status.rejected{background:#fff0f1;color:#c34653}.approval-note{display:flex;gap:.6rem;margin-top:1rem;padding:.75rem;border-radius:9px;background:#f4f1ff;color:#7055dc}.approval-note span,.approval-note strong{display:block;font-size:.67rem}@media(min-width:600px){.income-grid{grid-template-columns:repeat(2,1fr)}}@media(min-width:900px){.income-grid{grid-template-columns:repeat(4,1fr)}.income-head{flex-direction:row;align-items:center;justify-content:space-between}}
</style>
