<script setup>
import { computed,onMounted,ref } from 'vue';import DashboardLayout from '../../layouts/DashboardLayout.vue';import { getAuditLogs } from '../../services/audit.service.js';
const logs=ref([]);const loading=ref(false);const errorMessage=ref('');const selected=ref(null);const filters=ref({search:'',action:'',entity_type:'',from:'',to:''});
const actions=computed(()=>[...new Set(logs.value.map(item=>item.action))].sort());const entities=computed(()=>[...new Set(logs.value.map(item=>item.entity_type))].sort());
const load=async()=>{loading.value=true;errorMessage.value='';try{const params=Object.fromEntries(Object.entries(filters.value).filter(([,value])=>value));const response=await getAuditLogs(params);logs.value=response.data?.data||[];}catch(error){errorMessage.value=error.response?.data?.message||'Unable to load audit logs.';}finally{loading.value=false;}};const clear=()=>{filters.value={search:'',action:'',entity_type:'',from:'',to:''};load();};const label=value=>(value||'').replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase());const date=value=>new Date(value).toLocaleString();onMounted(load);
</script>
<template><DashboardLayout page-title="Audit Logs" page-subtitle="Security and accountability">
<section class="page-header"><div class="page-header-copy"><p class="page-header-label">Immutable activity history</p><h2>Audit logs</h2><p class="page-header-text mb-0">Investigate who created, edited, approved, rejected, reversed, or deleted sensitive records.</p></div><span class="security-badge"><i class="bi bi-lock-fill"></i>Immutable</span></section>
<div v-if="errorMessage" class="alert alert-warning">{{ errorMessage }}</div>
<section class="card panel-card filter-panel"><div class="card-body"><form class="filters" @submit.prevent="load"><label class="search"><i class="bi bi-search"></i><input v-model="filters.search" placeholder="User, action, record, or module" /></label><select v-model="filters.action" class="form-select"><option value="">All actions</option><option v-for="action in actions" :key="action" :value="action">{{ label(action) }}</option></select><select v-model="filters.entity_type" class="form-select"><option value="">All modules</option><option v-for="entity in entities" :key="entity" :value="entity">{{ label(entity) }}</option></select><input v-model="filters.from" class="form-control" type="date" aria-label="From date" /><input v-model="filters.to" class="form-control" type="date" aria-label="To date" /><button type="button" class="btn btn-outline-secondary" @click="clear">Clear</button><button class="btn btn-primary">Apply</button></form></div></section>
<section class="audit-summary"><article><small>Displayed events</small><strong>{{ logs.length }}</strong></article><article><small>Successful</small><strong class="success">{{ logs.filter(item=>item.outcome==='success').length }}</strong></article><article><small>Failed attempts</small><strong class="failed">{{ logs.filter(item=>item.outcome==='failed').length }}</strong></article><article><small>Users involved</small><strong>{{ new Set(logs.map(item=>item.user_id)).size }}</strong></article></section>
<section class="card panel-card"><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0 audit-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Record</th><th>Outcome</th><th>Address</th><th class="text-end">Details</th></tr></thead><tbody><tr v-if="loading"><td colspan="7" class="text-center py-5">Loading audit history...</td></tr><tr v-else-if="!logs.length"><td colspan="7" class="text-center py-5">No matching audit events.</td></tr><tr v-for="item in logs" v-else :key="item.id"><td><strong>{{ date(item.created_at) }}</strong><small>HTTP {{ item.status_code }}</small></td><td><strong>{{ item.user_name||'Deleted user' }}</strong><small>{{ label(item.user_role) }} · {{ item.user_email }}</small></td><td><span class="action" :class="item.action">{{ label(item.action) }}</span></td><td><strong>{{ label(item.entity_type) }}</strong><small>{{ item.entity_id?`Record #${item.entity_id}`:'General action' }}</small></td><td><span class="outcome" :class="item.outcome"><i class="bi" :class="item.outcome==='success'?'bi-check-circle':'bi-x-circle'"></i>{{ label(item.outcome) }}</span></td><td><span class="ip">{{ item.ip_address||'—' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-secondary" @click="selected=item">Inspect</button></td></tr></tbody></table></div></div></section>
<div v-if="selected" class="modal-backdrop"><div class="modal-panel audit-modal"><div class="modal-panel-header"><div><p class="page-header-label mb-2">Audit event #{{ selected.id }}</p><h5 class="mb-0">{{ label(selected.action) }} {{ label(selected.entity_type) }}</h5></div><button class="btn btn-close" @click="selected=null"></button></div><dl><div><dt>Performed by</dt><dd>{{ selected.user_name }} ({{ label(selected.user_role) }})</dd></div><div><dt>Timestamp</dt><dd>{{ date(selected.created_at) }}</dd></div><div><dt>Request</dt><dd><code>{{ selected.method }} {{ selected.path }}</code></dd></div><div><dt>Outcome</dt><dd>{{ label(selected.outcome) }} · HTTP {{ selected.status_code }}</dd></div><div><dt>Session</dt><dd><code>{{ selected.session_id||'Unavailable' }}</code></dd></div><div><dt>IP address</dt><dd>{{ selected.ip_address||'Unavailable' }}</dd></div><div><dt>User agent</dt><dd>{{ selected.user_agent||'Unavailable' }}</dd></div></dl><label>Sanitized change details</label><pre>{{ JSON.stringify(selected.details,null,2) }}</pre><div class="modal-actions"><button class="btn btn-primary" @click="selected=null">Done</button></div></div></div>
</DashboardLayout></template>
<style scoped>
.security-badge{display:inline-flex;align-items:center;gap:.4rem;padding:.45rem .65rem;border-radius:8px;background:#eeeaff;color:#6850ce;font-size:.68rem;font-weight:700}.filter-panel{margin-bottom:1rem}.filters{display:grid;gap:.5rem}.filters .search{display:flex;align-items:center;gap:.45rem;padding:0 .65rem;border:1px solid #dedbe4;border-radius:8px}.filters .search input{width:100%;border:0;outline:0;font-size:.7rem}.filters .form-select,.filters .form-control{font-size:.7rem}.audit-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:.7rem;margin-bottom:1rem}.audit-summary article{padding:.8rem;border:1px solid #ebe9ef;border-radius:10px;background:#fff}.audit-summary small,.audit-summary strong{display:block}.audit-summary small{color:#8d8993;font-size:.62rem}.audit-summary strong{margin-top:.2rem;font-size:1rem}.audit-summary .success{color:#168657}.audit-summary .failed{color:#c34653}.audit-table{min-width:950px}.audit-table td strong,.audit-table td small{display:block}.audit-table td small{margin-top:.15rem;color:#918d96;font-size:.62rem}.action,.outcome{display:inline-flex;align-items:center;gap:.3rem;padding:.27rem .5rem;border-radius:999px;font-size:.62rem}.action{background:#f0edff;color:#6850ce}.action.deleted,.action.rejected,.action.reversed{background:#fff0f1;color:#c34653}.action.approved,.action.created{background:#eaf9f1;color:#168657}.outcome.success{background:#eaf9f1;color:#168657}.outcome.failed{background:#fff0f1;color:#c34653}.ip{font-family:monospace;font-size:.66rem}.audit-modal{width:min(100%,620px)}.audit-modal dl{display:grid;gap:.35rem;margin:1rem 0}.audit-modal dl>div{display:grid;grid-template-columns:110px 1fr;gap:.7rem;padding:.45rem;border-bottom:1px solid #f0edf3}.audit-modal dt{color:#8c8792;font-size:.65rem}.audit-modal dd{margin:0;font-size:.68rem;overflow-wrap:anywhere}.audit-modal>label{font-size:.67rem;font-weight:700}.audit-modal pre{max-height:240px;overflow:auto;margin-top:.4rem;padding:.75rem;border-radius:8px;background:#25212c;color:#e8e2f1;font-size:.62rem}@media(min-width:700px){.filters{grid-template-columns:minmax(180px,1fr) repeat(4,minmax(110px,.55fr)) auto auto}.audit-summary{grid-template-columns:repeat(4,1fr)}}
</style>
