<script setup>
import { computed, onMounted, ref } from "vue";
import DashboardLayout from "../../layouts/DashboardLayout.vue";
import { createExpense, getExpenses } from "../../services/expense.service.js";
import { useAuthStore } from "../../stores/auth.store.js";

const categories=[['stationery','Stationery'],['mobile_money_charge','Mobile-money charges'],['meeting_cost','Meeting costs'],['registration_cost','Registration costs'],['bank_charge','Bank charges'],['transport','Transport'],['other','Other expense']];
const auth=useAuthStore(); const expenses=ref([]); const summary=ref({approved:0,pending:0,approved_count:0});
const loading=ref(false); const saving=ref(false); const showForm=ref(false); const filter=ref('all');
const errorMessage=ref(''); const successMessage=ref('');
const form=ref({category:'stationery',amount:'',payee:'',description:'',reference:'',expense_date:new Date().toISOString().slice(0,10)});
const canCreate=computed(()=>['admin','treasurer'].includes(auth.user?.role));
const filtered=computed(()=>filter.value==='all'?expenses.value:expenses.value.filter(item=>item.status===filter.value));
const currency=value=>new Intl.NumberFormat('en-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(value||0);
const label=value=>(categories.find(item=>item[0]===value)?.[1]||value);
const date=value=>value?new Date(value).toLocaleDateString():'—';
const load=async()=>{loading.value=true;errorMessage.value='';try{const response=await getExpenses();expenses.value=response.data?.data?.expenses||[];summary.value=response.data?.data?.summary||summary.value;}catch(error){errorMessage.value=error.response?.data?.message||'Unable to load expenses.';}finally{loading.value=false;}};
const close=()=>{showForm.value=false;errorMessage.value='';form.value={category:'stationery',amount:'',payee:'',description:'',reference:'',expense_date:new Date().toISOString().slice(0,10)};};
const submit=async()=>{saving.value=true;errorMessage.value='';try{const response=await createExpense({...form.value,amount:Number(form.value.amount),payee:form.value.payee||null,reference:form.value.reference||null});successMessage.value=response.data?.message||'Expense submitted for approval.';close();await load();}catch(error){errorMessage.value=error.response?.data?.message||'Unable to submit expense.';}finally{saving.value=false;}};
onMounted(load);
</script>

<template>
  <DashboardLayout page-title="Expenses" page-subtitle="Group operating costs">
    <section class="page-header"><div class="page-header-copy"><p class="page-header-label">Expense management</p><h2>Group expenses</h2><p class="page-header-text mb-0">Record operating costs and maintain approval-backed evidence for every payment.</p></div><button v-if="canCreate" class="btn btn-primary" @click="showForm=true"><i class="bi bi-plus-lg me-2"></i>New expense</button></section>
    <section class="row g-3 mb-4"><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Approved expenses</small><h3 class="info-card-value expense-value">{{ currency(summary.approved) }}</h3><p class="text-muted mb-0">Posted to the ledger</p></article></div><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Pending approval</small><h3 class="info-card-value pending-value">{{ currency(summary.pending) }}</h3><p class="text-muted mb-0">Not yet deducted</p></article></div><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Approved records</small><h3 class="info-card-value">{{ summary.approved_count }}</h3><p class="text-muted mb-0">Verified operating costs</p></article></div></section>
    <div v-if="errorMessage&&!showForm" class="alert alert-warning">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div>
    <section class="card panel-card"><div class="card-body"><div class="expense-head"><div><h5 class="mb-1">Expense register</h5><p class="text-muted mb-0">Pending items remain visible but enter the ledger only after approval.</p></div><div class="filters"><button v-for="item in [['all','All'],['pending','Pending'],['approved','Approved'],['rejected','Rejected']]" :key="item[0]" :class="{active:filter===item[0]}" @click="filter=item[0]">{{ item[1] }}</button></div></div><div class="table-responsive"><table class="table align-middle mb-0 expense-table"><thead><tr><th>Date</th><th>Category</th><th>Details</th><th>Payee</th><th>Reference</th><th>Requested by</th><th>Status</th><th class="text-end">Amount</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="text-center py-5">Loading expenses...</td></tr><tr v-else-if="!filtered.length"><td colspan="8" class="text-center py-5">No expenses found.</td></tr><tr v-for="item in filtered" v-else :key="item.id"><td>{{ date(item.expense_date) }}</td><td><span class="category"><i class="bi bi-receipt"></i>{{ label(item.category) }}</span></td><td><strong>{{ item.description }}</strong></td><td>{{ item.payee||'—' }}</td><td><code>{{ item.reference||`EXP-${item.id}` }}</code></td><td>{{ item.requested_by_name }}</td><td><span class="status" :class="item.status">{{ item.status }}</span></td><td class="text-end"><strong>{{ currency(item.amount) }}</strong></td></tr></tbody></table></div></div></section>
    <div v-if="showForm" class="modal-backdrop"><div class="modal-panel"><div class="modal-panel-header"><div><p class="page-header-label mb-2">New operating cost</p><h5 class="mb-0">Record expense</h5></div><button class="btn btn-close" @click="close"></button></div><form class="mt-3" @submit.prevent="submit"><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label">Category</label><select v-model="form.category" class="form-select"><option v-for="item in categories" :key="item[0]" :value="item[0]">{{ item[1] }}</option></select></div><div class="col-12 col-md-6"><label class="form-label">Expense date</label><input v-model="form.expense_date" class="form-control" type="date" required /></div><div class="col-12 col-md-6"><label class="form-label">Amount (TZS)</label><input v-model="form.amount" class="form-control" type="number" min="1" step="0.01" required /></div><div class="col-12 col-md-6"><label class="form-label">Paid to <span class="text-muted">(optional)</span></label><input v-model="form.payee" class="form-control" placeholder="Supplier or service provider" /></div><div class="col-12"><label class="form-label">Description</label><textarea v-model="form.description" class="form-control" rows="3" placeholder="What was purchased or paid for?" required></textarea></div><div class="col-12"><label class="form-label">Receipt / transaction reference <span class="text-muted">(optional)</span></label><input v-model="form.reference" class="form-control" placeholder="Receipt, bank, or mobile-money reference" /></div></div><div class="approval-note"><i class="bi bi-shield-check"></i><span><strong>Approval required</strong>This expense will not affect cash or the ledger until another authorized user approves it.</span></div><p v-if="errorMessage" class="text-danger small mt-3">{{ errorMessage }}</p><div class="modal-actions"><button type="button" class="btn btn-outline-secondary" @click="close">Cancel</button><button class="btn btn-primary" :disabled="saving">{{ saving?'Submitting...':'Submit for approval' }}</button></div></form></div></div>
  </DashboardLayout>
</template>

<style scoped>
.expense-value{color:#c34653!important}.pending-value{color:#a56a00!important}.expense-head{display:flex;flex-direction:column;gap:.8rem;margin-bottom:1rem}.filters{display:flex;gap:.25rem;padding:.25rem;border-radius:8px;background:#f5f4f7;overflow-x:auto}.filters button{padding:.4rem .6rem;border:0;border-radius:6px;background:transparent;color:#77727f;font-size:.66rem;white-space:nowrap}.filters button.active{background:#fff;color:#7055dc;box-shadow:0 1px 4px rgba(20,18,28,.08)}.expense-table{min-width:950px}.category{display:inline-flex;align-items:center;gap:.4rem;color:#625d69;font-size:.7rem}.category i{color:#7659e8}.expense-table code{color:#7055dc;font-size:.65rem}.status{display:inline-flex;padding:.27rem .55rem;border-radius:999px;font-size:.63rem;text-transform:capitalize}.status.pending{background:#fff5dd;color:#a56a00}.status.approved{background:#eaf9f1;color:#168657}.status.rejected{background:#fff0f1;color:#c34653}.approval-note{display:flex;gap:.65rem;margin-top:1rem;padding:.75rem;border-radius:9px;background:#f4f1ff;color:#7055dc}.approval-note span,.approval-note strong{display:block}.approval-note span{font-size:.67rem}.approval-note strong{margin-bottom:.15rem;font-size:.7rem}@media(min-width:700px){.expense-head{flex-direction:row;align-items:center;justify-content:space-between}}
</style>
