<script setup>
import { computed,onMounted,ref } from "vue";
import DashboardLayout from "../../layouts/DashboardLayout.vue";
import { cancelSubscription,createCheckout,getBillingOverview,getPlans } from "../../services/billing.service.js";
const plans=ref([]);const overview=ref(null);const loading=ref(true);const processing=ref(null);const errorMessage=ref("");const payment=ref(null);
const subscription=computed(()=>overview.value?.subscription||{});const canManage=computed(()=>overview.value?.membership?.role==="owner"||overview.value?.membership?.is_billing_admin);
const money=value=>new Intl.NumberFormat("en-TZ",{style:"currency",currency:"TZS",maximumFractionDigits:0}).format(value||0);
const date=value=>value?new Date(value).toLocaleDateString():"—";
const load=async()=>{loading.value=true;errorMessage.value="";try{const [planResponse,billingResponse]=await Promise.all([getPlans(),getBillingOverview()]);plans.value=planResponse.data.data;overview.value=billingResponse.data.data;}catch(error){errorMessage.value=error.response?.data?.message||"Unable to load billing.";}finally{loading.value=false;}};
const choose=async plan=>{processing.value=plan.id;errorMessage.value="";try{const response=await createCheckout(plan.id);payment.value=response.data.data;if(payment.value.checkout_url)window.open(payment.value.checkout_url,"_blank","noopener");await load();}catch(error){errorMessage.value=error.response?.data?.message||"Unable to create payment request.";}finally{processing.value=null;}};
const cancel=async()=>{if(!confirm("Cancel renewal at the end of the current billing period?"))return;try{await cancelSubscription();await load();}catch(error){errorMessage.value=error.response?.data?.message||"Unable to cancel subscription.";}};onMounted(load);
</script>
<template><DashboardLayout page-title="Plans & Billing" page-subtitle="Subscription management">
<section class="page-header"><div class="page-header-copy"><p class="page-header-label">{{ overview?.organization?.name }}</p><h2>Plans & billing</h2><p class="page-header-text mb-0">Manage your group subscription, payments, invoices, and trial status.</p></div></section>
<div v-if="errorMessage" class="alert alert-warning">{{ errorMessage }}</div><div v-if="loading" class="billing-empty">Loading billing...</div><template v-else>
<section class="current"><div><span>Current status</span><strong>{{ subscription.status }}</strong><small v-if="subscription.status==='trialing'">{{ subscription.days_remaining }} trial days remaining</small><small v-else>Current period ends {{ date(subscription.current_period_ends_at) }}</small></div><div><span>Current plan</span><strong>{{ subscription.plan_name }}</strong><small>{{ subscription.member_limit?`Up to ${subscription.member_limit} members`:'Unlimited members' }}</small></div><button v-if="canManage&&subscription.status==='active'&&!subscription.cancel_at_period_end" class="btn btn-outline-danger" @click="cancel">Cancel renewal</button></section>
<div v-if="payment" class="alert alert-success"><strong>Payment request created.</strong> Reference <code>{{ payment.payment.reference }}</code> for {{ money(payment.payment.amount_tzs) }}. Subscription access changes only after verified payment confirmation.</div>
<section class="plans"><article v-for="plan in plans" :key="plan.id" :class="{selected:plan.code===subscription.plan_code}"><span class="interval">{{ plan.billing_interval }}</span><h3>{{ plan.name }}</h3><p>{{ plan.description }}</p><strong class="price">{{ money(plan.price_tzs) }}<small>/{{ plan.billing_interval }}</small></strong><ul><li>{{ plan.member_limit?`Up to ${plan.member_limit} members`:'Unlimited members' }}</li><li>Reports and exports</li><li>Approvals and audit logs</li><li v-if="plan.features.priority_support">Priority support</li></ul><button v-if="canManage" class="btn btn-primary" :disabled="processing===plan.id||plan.code===subscription.plan_code&&subscription.status==='active'" @click="choose(plan)">{{ processing===plan.id?'Creating payment...':plan.code===subscription.plan_code&&subscription.status==='active'?'Current plan':'Choose plan' }}</button></article></section>
<section class="card panel-card"><div class="card-body"><h5>Invoices & payments</h5><div class="table-responsive"><table class="table"><thead><tr><th>Invoice</th><th>Date</th><th>Status</th><th>Due</th><th class="text-end">Amount</th></tr></thead><tbody><tr v-if="!overview.invoices.length"><td colspan="5" class="text-center py-4">No invoices yet.</td></tr><tr v-for="invoice in overview.invoices" :key="invoice.id"><td><code>{{ invoice.invoice_number }}</code></td><td>{{ date(invoice.created_at) }}</td><td>{{ invoice.status }}</td><td>{{ date(invoice.due_at) }}</td><td class="text-end">{{ money(invoice.amount_tzs) }}</td></tr></tbody></table></div></div></section></template>
</DashboardLayout></template>
<style scoped>.billing-empty{padding:3rem;text-align:center}.current{display:grid;gap:1rem;align-items:center;margin-bottom:1rem;padding:1rem;border-radius:13px;background:linear-gradient(135deg,#30234d,#7053d7);color:#fff}.current span,.current strong,.current small{display:block}.current span{color:#cfc3f5;font-size:.65rem;text-transform:uppercase}.current strong{margin:.25rem 0;text-transform:capitalize}.current small{color:#ddd6f2;font-size:.68rem}.plans{display:grid;gap:.8rem;margin-bottom:1rem}.plans article{position:relative;padding:1rem;border:1px solid #e7e3ed;border-radius:12px;background:#fff}.plans article.selected{border-color:#7659e8;box-shadow:0 0 0 2px #eeeaff}.plans h3{font-size:1rem}.plans p,.plans li{color:#7c7882;font-size:.68rem}.plans ul{padding-left:1rem}.price{display:block;margin:.8rem 0;font-size:1.25rem}.price small{font-size:.65rem}.interval{position:absolute;right:.8rem;top:.8rem;padding:.25rem .45rem;border-radius:99px;background:#f0edff;color:#7056dc;font-size:.6rem;text-transform:uppercase}@media(min-width:700px){.current{grid-template-columns:1fr 1fr auto}.plans{grid-template-columns:repeat(3,1fr)}}
</style>
