<script setup>
import { computed, onMounted, ref } from "vue";
import DashboardLayout from "../../layouts/DashboardLayout.vue";
import { getMembers } from "../../services/member.service.js";
import { createSocialFundEntry, getSocialFund } from "../../services/socialFund.service.js";
import { useAuthStore } from "../../stores/auth.store.js";

const authStore = useAuthStore();
const entries = ref([]); const summary = ref({ contributions: 0, disbursements: 0, balance: 0, pending: 0 });
const members = ref([]); const loading = ref(false); const saving = ref(false); const errorMessage = ref(""); const successMessage = ref(""); const showForm = ref(false);
const filter = ref("all");
const form = ref({ entry_type: "contribution", member_id: "", beneficiary_name: "", category: "sickness", amount: "", description: "", reference: "" });
const canRecord = computed(() => ["admin", "treasurer"].includes(authStore.user?.role));
const filtered = computed(() => filter.value === "all" ? entries.value : entries.value.filter((entry) => entry.entry_type === filter.value));
const currency = (value) => new Intl.NumberFormat("en-TZ", { style: "currency", currency: "TZS", maximumFractionDigits: 0 }).format(value || 0);
const categoryLabel = (value) => value.charAt(0).toUpperCase() + value.slice(1).replaceAll("_", " ");
const load = async () => { loading.value = true; errorMessage.value = ""; try { const [fundResponse, memberResponse] = await Promise.all([getSocialFund(), getMembers()]); entries.value = fundResponse.data?.data?.entries || []; summary.value = fundResponse.data?.data?.summary || summary.value; members.value = memberResponse.data?.data || []; } catch (error) { errorMessage.value = error.response?.data?.message || "Unable to load social fund."; } finally { loading.value = false; } };
const closeForm = () => { showForm.value = false; errorMessage.value = ""; form.value = { entry_type: "contribution", member_id: "", beneficiary_name: "", category: "sickness", amount: "", description: "", reference: "" }; };
const submit = async () => { saving.value = true; errorMessage.value = ""; try { const response = await createSocialFundEntry({ ...form.value, member_id: form.value.member_id || null, amount: Number(form.value.amount), reference: form.value.reference || null }); successMessage.value = response.data?.message || (form.value.entry_type === "contribution" ? "Contribution recorded." : "Support payment submitted for approval."); closeForm(); await load(); } catch (error) { errorMessage.value = error.response?.data?.message || "Unable to save social-fund entry."; } finally { saving.value = false; } };
onMounted(load);
</script>

<template>
  <DashboardLayout page-title="Social Fund" page-subtitle="Emergency and welfare support">
    <section class="page-header"><div class="page-header-copy"><p class="page-header-label">Separate welfare fund</p><h2>Social / Emergency Fund</h2><p class="page-header-text mb-0">Manage sickness, funeral, emergency, and agreed support without mixing funds with normal savings.</p></div><button v-if="canRecord" class="btn btn-primary" @click="showForm=true"><i class="bi bi-plus-lg me-2"></i>New fund entry</button></section>
    <section class="row g-3 mb-4"><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Fund balance</small><h3 class="info-card-value balance-text">{{ currency(summary.balance) }}</h3><p class="text-muted mb-0">Available for approved support</p></article></div><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Contributions</small><h3 class="info-card-value contribution-text">{{ currency(summary.contributions) }}</h3><p class="text-muted mb-0">Kept separate from savings</p></article></div><div class="col-12 col-sm-4"><article class="info-card"><small class="info-card-label">Support distributed</small><h3 class="info-card-value support-text">{{ currency(summary.disbursements) }}</h3><p class="text-muted mb-0">Approved social assistance</p></article></div></section>
    <div v-if="errorMessage && !showForm" class="alert alert-warning">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div>
    <div v-if="summary.pending" class="alert alert-info"><i class="bi bi-clock-history me-2"></i>{{ summary.pending }} support {{ summary.pending === 1 ? 'request is' : 'requests are' }} waiting for approval. Pending requests are shown below but do not reduce the fund balance.</div>
    <section class="card panel-card"><div class="card-body"><div class="fund-head"><div><h5 class="mb-1">Fund activity</h5><p class="text-muted mb-0">Dedicated social-fund contributions and approved support.</p></div><div class="fund-filters"><button :class="{active:filter==='all'}" @click="filter='all'">All</button><button :class="{active:filter==='contribution'}" @click="filter='contribution'">Contributions</button><button :class="{active:filter==='disbursement'}" @click="filter='disbursement'">Support</button></div></div><div class="table-responsive"><table class="table align-middle mb-0 fund-table"><thead><tr><th>Date</th><th>Type</th><th>Member / Beneficiary</th><th>Purpose</th><th>Reference</th><th>Recorded by</th><th class="text-end">Amount</th></tr></thead><tbody><tr v-if="loading"><td colspan="7" class="text-center py-5">Loading social fund...</td></tr><tr v-else-if="!filtered.length"><td colspan="7" class="text-center py-5">No social-fund entries found.</td></tr><tr v-for="entry in filtered" v-else :key="entry.id"><td>{{ new Date(entry.created_at).toLocaleDateString() }}</td><td><span class="entry-type" :class="entry.entry_type">{{ entry.entry_type === 'contribution' ? 'Contribution' : categoryLabel(entry.category) }}</span></td><td><strong>{{ entry.entry_type === 'contribution' ? `${entry.first_name} ${entry.last_name}` : entry.beneficiary_name }}</strong></td><td>{{ entry.description }}</td><td><code>{{ entry.reference || `SF-${entry.id}` }}</code></td><td>{{ entry.recorded_by_name || 'System' }}</td><td class="text-end"><strong :class="entry.entry_type === 'contribution' ? 'contribution-text' : 'support-text'">{{ entry.entry_type === 'contribution' ? '+' : '−' }} {{ currency(entry.amount) }}</strong></td></tr></tbody></table></div></div></section>
    <div v-if="showForm" class="modal-backdrop"><div class="modal-panel"><div class="modal-panel-header"><div><p class="page-header-label mb-2">Social fund</p><h5 class="mb-0">Record fund activity</h5></div><button class="btn btn-close" @click="closeForm"></button></div><form class="mt-3" @submit.prevent="submit"><div class="entry-switch"><button type="button" :class="{active:form.entry_type==='contribution'}" @click="form.entry_type='contribution'">Member contribution</button><button type="button" :class="{active:form.entry_type==='disbursement'}" @click="form.entry_type='disbursement'">Support payment</button></div><div class="row g-3"><div v-if="form.entry_type==='contribution'" class="col-12"><label class="form-label">Contributing member</label><select v-model="form.member_id" class="form-select" required><option value="" disabled>Select a member</option><option v-for="member in members" :key="member.id" :value="member.id">{{ member.first_name }} {{ member.last_name }} — {{ member.phone }}</option></select></div><template v-else><div class="col-12 col-md-6"><label class="form-label">Support category</label><select v-model="form.category" class="form-select"><option value="sickness">Sickness</option><option value="funeral">Funeral</option><option value="emergency">Emergency</option><option value="other">Other agreed support</option></select></div><div class="col-12 col-md-6"><label class="form-label">Beneficiary</label><input v-model="form.beneficiary_name" class="form-control" required /></div><div class="col-12"><label class="form-label">Related member <span class="text-muted">(optional)</span></label><select v-model="form.member_id" class="form-select"><option value="">No linked member</option><option v-for="member in members" :key="member.id" :value="member.id">{{ member.first_name }} {{ member.last_name }}</option></select></div></template><div class="col-12 col-md-6"><label class="form-label">Amount (TZS)</label><input v-model="form.amount" class="form-control" type="number" min="1" required /></div><div class="col-12 col-md-6"><label class="form-label">Reference</label><input v-model="form.reference" class="form-control" placeholder="Receipt or voucher" /></div><div class="col-12"><label class="form-label">Description</label><textarea v-model="form.description" class="form-control" rows="3" required></textarea></div></div><div v-if="form.entry_type==='disbursement'" class="approval-notice"><i class="bi bi-shield-check"></i>This support payment will require another authorized user’s approval.</div><p v-if="errorMessage" class="text-danger small mt-3">{{ errorMessage }}</p><div class="modal-actions"><button type="button" class="btn btn-outline-secondary" @click="closeForm">Cancel</button><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Saving...' : form.entry_type==='contribution' ? 'Record contribution' : 'Request approval' }}</button></div></form></div></div>
  </DashboardLayout>
</template>

<style scoped>
.balance-text{color:#7056dc!important}.contribution-text{color:#168657!important}.support-text{color:#cf4b58!important}.fund-head{display:flex;flex-direction:column;gap:.8rem;margin-bottom:1rem}.fund-filters,.entry-switch{display:flex;gap:.3rem;padding:.25rem;border-radius:8px;background:#f5f5f7}.fund-filters button,.entry-switch button{padding:.45rem .65rem;border:0;border-radius:6px;background:transparent;color:#74737c;font-size:.68rem}.fund-filters button.active,.entry-switch button.active{background:#fff;color:#7056dc;box-shadow:0 1px 4px rgba(24,24,27,.08)}.fund-table{min-width:850px}.entry-type{display:inline-flex;padding:.28rem .55rem;border-radius:999px;font-size:.64rem}.entry-type.contribution{background:#eaf9f1;color:#168657}.entry-type.disbursement{background:#fff0f1;color:#cf4b58}.fund-table code{color:#7056dc;font-size:.66rem}.entry-switch{margin-bottom:1rem}.entry-switch button{flex:1}.approval-notice{display:flex;align-items:center;gap:.45rem;margin-top:1rem;padding:.7rem;border-radius:8px;background:#f7f5ff;color:#7056dc;font-size:.68rem}@media(min-width:700px){.fund-head{flex-direction:row;align-items:center;justify-content:space-between}}
</style>
