<script setup>
import { computed,onMounted,ref } from 'vue';
import DashboardLayout from '../../layouts/DashboardLayout.vue';
import { getShareouts,requestShareoutPayment } from '../../services/shareout.service.js';
import { useAuthStore } from '../../stores/auth.store.js';
const auth=useAuthStore();const records=ref([]);const loading=ref(false);const processing=ref(null);const errorMessage=ref('');const successMessage=ref('');const cycleFilter=ref('all');
const canPay=computed(()=>['admin','treasurer'].includes(auth.user?.role));
const cycles=computed(()=>[...new Map(records.value.map(item=>[item.cycle_id,item.cycle_name])).entries()]);
const filtered=computed(()=>cycleFilter.value==='all'?records.value:records.value.filter(item=>String(item.cycle_id)===String(cycleFilter.value)));
const totals=computed(()=>filtered.value.reduce((sum,item)=>{sum.savings+=Number(item.savings_amount);sum.shares+=Number(item.shares_value||0);sum.profit+=Number(item.earnings_share);sum.total+=Number(item.projected_shareout);if(item.distribution_status==='paid')sum.paid+=Number(item.projected_shareout);return sum;},{savings:0,shares:0,profit:0,total:0,paid:0}));
const currency=value=>new Intl.NumberFormat('en-TZ',{style:'currency',currency:'TZS',maximumFractionDigits:0}).format(value||0);
const percent=value=>`${(Number(value||0)*100).toFixed(2)}%`;
const load=async()=>{loading.value=true;errorMessage.value='';try{const response=await getShareouts();records.value=response.data?.data||[];}catch(error){errorMessage.value=error.response?.data?.message||'Unable to load share-out records.';}finally{loading.value=false;}};
const requestPayment=async item=>{processing.value=item.id;errorMessage.value='';try{const response=await requestShareoutPayment(item.id);successMessage.value=response.data?.message||'Payment submitted for approval.';await load();}catch(error){errorMessage.value=error.response?.data?.message||'Unable to request payment.';}finally{processing.value=null;}};
onMounted(load);
</script>
<template><DashboardLayout page-title="Share-out" page-subtitle="Cycle profit distribution">
  <section class="page-header"><div class="page-header-copy"><p class="page-header-label">End-of-cycle distribution</p><h2>Share-out & profit distribution</h2><p class="page-header-text mb-0">Return member savings and Hisa capital, then allocate realized profit according to each member’s combined capital proportion.</p></div><select v-model="cycleFilter" class="form-select cycle-select"><option value="all">All closed cycles</option><option v-for="cycle in cycles" :key="cycle[0]" :value="cycle[0]">{{ cycle[1] }}</option></select></section>
  <div v-if="errorMessage" class="alert alert-warning">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div>
  <section class="row g-3 mb-4"><div class="col-6 col-xl-3"><article class="info-card"><small class="info-card-label">Savings + Hisa</small><h3 class="info-card-value">{{ currency(totals.savings+totals.shares) }}</h3></article></div><div class="col-6 col-xl-3"><article class="info-card"><small class="info-card-label">Allocated profit</small><h3 class="info-card-value profit">{{ currency(totals.profit) }}</h3></article></div><div class="col-6 col-xl-3"><article class="info-card"><small class="info-card-label">Total distribution</small><h3 class="info-card-value total">{{ currency(totals.total) }}</h3></article></div><div class="col-6 col-xl-3"><article class="info-card"><small class="info-card-label">Paid out</small><h3 class="info-card-value paid">{{ currency(totals.paid) }}</h3></article></div></section>
  <section class="calculation-note"><i class="bi bi-calculator"></i><div><strong>How profit is allocated</strong><span>Member profit = distributable profit × ((member savings + Hisa value) ÷ total group capital). Distributable profit includes realized loan interest, fines, and other income, less approved expenses.</span></div></section>
  <section class="card panel-card"><div class="card-body"><div class="panel-heading"><div><h5 class="mb-1">Member distributions</h5><p class="text-muted mb-0">Closing snapshots cannot change after a cycle closes.</p></div><span>{{ filtered.length }} members</span></div><div class="table-responsive"><table class="table align-middle mb-0 share-table"><thead><tr><th>Cycle</th><th>Member</th><th class="text-end">Savings</th><th class="text-end">Share ratio</th><th class="text-end">Profit share</th><th class="text-end">Final share-out</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="text-center py-5">Calculating distributions...</td></tr><tr v-else-if="!filtered.length"><td colspan="8" class="text-center py-5">Close a financial cycle to create share-out records.</td></tr><tr v-for="item in filtered" v-else :key="item.id"><td><strong>{{ item.cycle_name }}</strong></td><td><strong>{{ item.first_name }} {{ item.last_name }}</strong><small>{{ item.phone }}</small></td><td class="text-end">{{ currency(item.savings_amount) }}</td><td class="text-end"><span class="ratio">{{ percent(item.savings_ratio) }}</span></td><td class="text-end profit-text">+ {{ currency(item.earnings_share) }}</td><td class="text-end"><strong>{{ currency(item.projected_shareout) }}</strong></td><td><span class="status" :class="item.distribution_status==='paid'?'paid':item.approval_status==='pending'?'pending':'unpaid'">{{ item.distribution_status==='paid'?'Paid':item.approval_status==='pending'?'Awaiting approval':'Unpaid' }}</span></td><td class="text-end"><button v-if="canPay&&item.distribution_status!=='paid'&&item.approval_status!=='pending'" class="btn btn-sm btn-outline-primary" :disabled="processing===item.id" @click="requestPayment(item)">{{ processing===item.id?'Submitting...':'Request payout' }}</button><span v-else-if="item.distribution_status==='paid'" class="paid-date">Completed</span></td></tr></tbody></table></div></div></section>
</DashboardLayout></template>
<style scoped>
.cycle-select{width:100%;max-width:220px}.profit{color:#168657!important}.total{color:#7055dc!important}.paid{color:#2877c7!important}.calculation-note{display:flex;gap:.75rem;margin-bottom:1rem;padding:1rem;border:1px solid #e4def8;border-radius:11px;background:#f8f6ff;color:#65509f}.calculation-note i{font-size:1.25rem}.calculation-note strong,.calculation-note span{display:block}.calculation-note strong{font-size:.77rem}.calculation-note span{margin-top:.2rem;color:#81779b;font-size:.68rem;line-height:1.5}.panel-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem}.panel-heading>span{font-size:.68rem;color:#8c8792}.share-table{min-width:980px}.share-table td small{display:block;color:#908b95;font-size:.64rem}.ratio{padding:.25rem .45rem;border-radius:6px;background:#f1eff7;color:#675b79;font-size:.65rem}.profit-text{color:#168657}.status{display:inline-flex;padding:.27rem .55rem;border-radius:999px;font-size:.62rem}.status.paid{background:#eaf9f1;color:#168657}.status.pending{background:#fff5dd;color:#a56a00}.status.unpaid{background:#f1f1f3;color:#706d75}.paid-date{color:#168657;font-size:.66rem}@media(min-width:700px){.cycle-select{width:220px}}
</style>
