<script setup>
import { computed, onMounted, ref } from "vue";
import DashboardLayout from "../../layouts/DashboardLayout.vue";
import { activateCycle, closeCycle, createCycle, getCycles } from "../../services/cycle.service.js";
import { useAuthStore } from "../../stores/auth.store.js";

const auth = useAuthStore();
const cycles = ref([]); const loading = ref(false); const saving = ref(false);
const errorMessage = ref(""); const successMessage = ref("");
const showCreate = ref(false); const closingCycle = ref(null); const expanded = ref(null);
const form = ref({ name: `${new Date().getFullYear()} Cycle`, start_date: "", end_date: "" });
const closeNotes = ref("");
const canManage = computed(() => ["admin", "chairperson", "treasurer"].includes(auth.user?.role));
const activeCycle = computed(() => cycles.value.find((cycle) => cycle.status === "active"));
const currency = (value) => new Intl.NumberFormat("en-TZ", { style: "currency", currency: "TZS", maximumFractionDigits: 0 }).format(value || 0);
const date = (value) => value ? new Date(value).toLocaleDateString() : "—";
const load = async () => { loading.value=true; errorMessage.value=""; try { const response=await getCycles(); cycles.value=response.data?.data||[]; } catch(error) { errorMessage.value=error.response?.data?.message||"Unable to load financial cycles."; } finally { loading.value=false; } };
const create = async () => { saving.value=true; errorMessage.value=""; try { await createCycle(form.value); showCreate.value=false; form.value={ name:`${new Date().getFullYear()} Cycle`,start_date:"",end_date:"" }; successMessage.value="Financial cycle created as draft."; await load(); } catch(error) { errorMessage.value=error.response?.data?.message||"Unable to create cycle."; } finally { saving.value=false; } };
const activate = async (cycle) => { saving.value=true; errorMessage.value=""; try { await activateCycle(cycle.id); successMessage.value=`${cycle.name} is now active.`; await load(); } catch(error) { errorMessage.value=error.response?.data?.message||"Unable to activate cycle."; } finally { saving.value=false; } };
const close = async () => { saving.value=true; errorMessage.value=""; try { await closeCycle(closingCycle.value.id,{notes:closeNotes.value}); successMessage.value=`${closingCycle.value.name} closed and its share-out snapshot was saved.`; closingCycle.value=null; closeNotes.value=""; await load(); } catch(error) { errorMessage.value=error.response?.data?.message||"Unable to close cycle."; } finally { saving.value=false; } };
onMounted(load);
</script>

<template>
  <DashboardLayout page-title="Financial Cycles" page-subtitle="Periods and share-out">
    <section class="page-header"><div class="page-header-copy"><p class="page-header-label">Financial period</p><h2>Cycles & closing</h2><p class="page-header-text mb-0">Define the group operating period and preserve an end-of-cycle share-out snapshot.</p></div><button v-if="canManage" class="btn btn-primary" @click="showCreate=true"><i class="bi bi-plus-lg me-2"></i>New cycle</button></section>
    <div v-if="errorMessage" class="alert alert-warning">{{ errorMessage }}</div><div v-if="successMessage" class="alert alert-success">{{ successMessage }}</div>
    <section v-if="activeCycle" class="active-cycle"><div><span>Active cycle</span><h3>{{ activeCycle.name }}</h3><p>{{ date(activeCycle.start_date) }} — {{ date(activeCycle.end_date) }}</p></div><div class="cycle-progress"><i class="bi bi-calendar-check"></i><span>Financial activity within these dates will be included at closing.</span></div><button v-if="canManage" class="btn btn-outline-danger" @click="closingCycle=activeCycle">Close cycle</button></section>
    <section v-else-if="!loading" class="no-active"><i class="bi bi-calendar2-range"></i><div><strong>No active financial cycle</strong><span>Create a draft cycle or activate an existing draft.</span></div></section>
    <section class="card panel-card"><div class="card-body"><div class="panel-heading"><div><h5 class="mb-1">Cycle history</h5><p class="text-muted mb-0">Draft, active, and permanently closed financial periods.</p></div><span>{{ cycles.length }} cycles</span></div><div class="cycle-list"><div v-if="loading" class="empty-state">Loading cycles...</div><div v-else-if="!cycles.length" class="empty-state">No financial cycles created.</div><article v-for="cycle in cycles" v-else :key="cycle.id" class="cycle-row"><div class="cycle-main"><span class="cycle-icon"><i class="bi bi-calendar3"></i></span><div><strong>{{ cycle.name }}</strong><small>{{ date(cycle.start_date) }} — {{ date(cycle.end_date) }}</small></div></div><span class="status" :class="cycle.status">{{ cycle.status }}</span><div v-if="cycle.closing_summary" class="summary"><span>Savings <strong>{{ currency(cycle.closing_summary.totalSavings) }}</strong></span><span>Earnings <strong>{{ currency(cycle.closing_summary.distributableEarnings) }}</strong></span><span>Projected share-out <strong>{{ currency(cycle.closing_summary.projectedShareout) }}</strong></span><span>Outstanding loans <strong>{{ currency(cycle.closing_summary.outstandingLoans) }}</strong></span></div><div class="cycle-actions"><button v-if="cycle.status==='draft'&&canManage" class="btn btn-sm btn-outline-primary" :disabled="saving||!!activeCycle" @click="activate(cycle)">Activate</button><button v-if="cycle.status==='active'&&canManage" class="btn btn-sm btn-outline-danger" @click="closingCycle=cycle">Close</button><button v-if="cycle.status==='closed'" class="btn btn-sm btn-outline-secondary" @click="expanded=expanded===cycle.id?null:cycle.id">{{ expanded===cycle.id?'Hide':'View' }} share-out</button></div><div v-if="expanded===cycle.id" class="snapshot"><div v-for="member in cycle.member_snapshots" :key="member.member_id"><span>{{ member.first_name }} {{ member.last_name }}</span><small>Savings {{ currency(member.savings_amount) }} + earnings {{ currency(member.earnings_share) }}</small><strong>{{ currency(member.projected_shareout) }}</strong></div></div></article></div></div></section>
    <div v-if="showCreate" class="modal-backdrop"><div class="modal-panel"><div class="modal-panel-header"><div><p class="page-header-label mb-2">New period</p><h5 class="mb-0">Create financial cycle</h5></div><button class="btn btn-close" @click="showCreate=false"></button></div><form class="mt-3" @submit.prevent="create"><div class="row g-3"><div class="col-12"><label class="form-label">Cycle name</label><input v-model="form.name" class="form-control" placeholder="2026 Cycle" required /></div><div class="col-12 col-sm-6"><label class="form-label">Start date</label><input v-model="form.start_date" class="form-control" type="date" required /></div><div class="col-12 col-sm-6"><label class="form-label">End date</label><input v-model="form.end_date" class="form-control" type="date" required /></div></div><div class="modal-actions"><button type="button" class="btn btn-outline-secondary" @click="showCreate=false">Cancel</button><button class="btn btn-primary" :disabled="saving">{{ saving?'Creating...':'Create draft' }}</button></div></form></div></div>
    <div v-if="closingCycle" class="modal-backdrop"><div class="modal-panel"><div class="modal-panel-header"><div><p class="page-header-label mb-2">Closing process</p><h5 class="mb-0">Close {{ closingCycle.name }}</h5></div><button class="btn btn-close" @click="closingCycle=null"></button></div><div class="close-warning"><i class="bi bi-lock"></i><p><strong>This creates a permanent closing snapshot.</strong><span>Member savings, earnings allocation, cash movement, and outstanding loans will be captured.</span></p></div><label class="form-label">Closing notes</label><textarea v-model="closeNotes" class="form-control" rows="3" placeholder="Resolutions, exceptions, or share-out notes"></textarea><div class="modal-actions"><button class="btn btn-outline-secondary" @click="closingCycle=null">Cancel</button><button class="btn btn-danger" :disabled="saving" @click="close">{{ saving?'Closing...':'Confirm closing' }}</button></div></div></div>
  </DashboardLayout>
</template>

<style scoped>
.active-cycle{display:flex;flex-direction:column;gap:1rem;margin-bottom:1rem;padding:1.2rem;border-radius:14px;background:linear-gradient(135deg,#30234d,#7053d7);color:#fff}.active-cycle>div>span{color:#cbbef7;font-size:.67rem;text-transform:uppercase}.active-cycle h3{margin:.25rem 0;font-size:1.4rem}.active-cycle p{margin:0;color:rgba(255,255,255,.65);font-size:.76rem}.cycle-progress{display:flex;align-items:center;gap:.6rem;padding:.7rem;border-radius:9px;background:rgba(255,255,255,.09);font-size:.7rem}.no-active{display:flex;align-items:center;gap:.8rem;margin-bottom:1rem;padding:1rem;border:1px dashed #d9d4e7;border-radius:12px;background:#faf9fd}.no-active i{font-size:1.4rem;color:#7659e8}.no-active strong,.no-active span{display:block}.no-active span{color:#89858f;font-size:.7rem}.panel-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}.panel-heading>span{color:#817c89;font-size:.7rem}.cycle-list{display:grid;gap:.7rem}.cycle-row{display:grid;gap:.8rem;padding:1rem;border:1px solid #ece9f1;border-radius:11px}.cycle-main{display:flex;align-items:center;gap:.7rem}.cycle-main>div strong,.cycle-main>div small{display:block}.cycle-main>div small{margin-top:.2rem;color:#8e8995;font-size:.67rem}.cycle-icon{width:2.2rem;height:2.2rem;display:grid;place-items:center;border-radius:8px;background:#f0edff;color:#7054db}.status{width:max-content;padding:.27rem .55rem;border-radius:999px;font-size:.63rem;text-transform:capitalize}.status.draft{background:#f1f1f3;color:#737078}.status.active{background:#eaf9f1;color:#168657}.status.closed{background:#ece8fb;color:#6249c4}.summary{display:grid;grid-template-columns:repeat(2,1fr);gap:.45rem}.summary span{padding:.55rem;border-radius:7px;background:#faf9fc;color:#89848f;font-size:.62rem}.summary strong{display:block;margin-top:.2rem;color:#29262e;font-size:.7rem}.cycle-actions{display:flex;gap:.45rem}.snapshot{display:grid;gap:.35rem;padding-top:.7rem;border-top:1px solid #eeeaf2}.snapshot>div{display:grid;grid-template-columns:1fr auto;gap:.15rem .7rem;padding:.55rem;border-radius:7px;background:#faf9fc;font-size:.7rem}.snapshot small{color:#8d8894}.snapshot strong{grid-row:span 2;align-self:center}.close-warning{display:flex;gap:.7rem;margin:1rem 0;padding:.8rem;border-radius:9px;background:#fff6e5;color:#8e650e}.close-warning p,.close-warning strong,.close-warning span{display:block;margin:0}.close-warning span{margin-top:.2rem;font-size:.68rem}.empty-state{padding:2rem;text-align:center;color:#8d8993}@media(min-width:700px){.active-cycle{display:grid;grid-template-columns:1fr minmax(260px,.7fr) auto;align-items:center}.cycle-row{grid-template-columns:minmax(180px,1fr) auto minmax(300px,1.4fr) auto;align-items:center}.snapshot{grid-column:1/-1}.summary{grid-template-columns:repeat(4,1fr)}}
</style>
